baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[security]
  enableInlineShortcodes = true
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', '^WC_POST_CSS']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']